spring:
  application:
    name: eureka-server

server:
  port: 8761

eureka:
  client:
    allow-redirects: false
    register-with-eureka: false

management:
  tracing:
    sampling:
      # Trace every action
      probability: 1.0

